[package]
name = "js_arc"
version = "0.1.0"
edition = "2021"
license = "MIT"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
async-channel = "2"
once_cell = "1"
wasm-bindgen = "0.2"
wasm-bindgen-futures = "0.4"

